<?php

use Illuminate\Database\Seeder;

class CursoSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $register = [
            ['nome'=>'Agente Comunitário de Saúde','tipo'=>'tecnico'],
            ['nome'=>'Análises Clínicas','tipo'=>'tecnico'],
            ['nome'=>'Biotecnologia','tipo'=>'tecnico'],
            ['nome'=>'Citopatologia','tipo'=>'tecnico'],
            ['nome'=>'Controle Ambiental','tipo'=>'tecnico'],
            ['nome'=>'Enfermagem','tipo'=>'tecnico'],
            ['nome'=>'Equipamentos Biomédicos','tipo'=>'tecnico'],
            ['nome'=>'Estética','tipo'=>'tecnico'],
            ['nome'=>'Farmácia','tipo'=>'tecnico'],
            ['nome'=>'Gerência em Saúde','tipo'=>'tecnico'],
            ['nome'=>'Hemoterapia','tipo'=>'tecnico'],
            ['nome'=>'Saúde Bucal','tipo'=>'tecnico'],
            ['nome'=>'Imagem Pessoal','tipo'=>'tecnico'],
            ['nome'=>'Imobilizações Ortopédicas','tipo'=>'tecnico'],
            ['nome'=>'Massoterapia','tipo'=>'tecnico'],
            ['nome'=>'MeioAmbiente','tipo'=>'tecnico'],
            ['nome'=>'Meteorologia','tipo'=>'tecnico'],
            ['nome'=>'Nutrição e Dietética','tipo'=>'tecnico'],
            ['nome'=>'Óptica','tipo'=>'tecnico'],
            ['nome'=>'Órtesese Próteses','tipo'=>'tecnico'],
            ['nome'=>'Podologia','tipo'=>'tecnico'],
            ['nome'=>'PróteseDentária','tipo'=>'tecnico'],
            ['nome'=>'Radiologia','tipo'=>'tecnico'],
            ['nome'=>'Reabilitação de Dependentes Químicos','tipo'=>'tecnico'],
            ['nome'=>'Reciclagem','tipo'=>'tecnico'],
            ['nome'=>'Registrose Informações em Saúde','tipo'=>'tecnico'],
            ['nome'=>'Segurança do Trabalho','tipo'=>'tecnico'],
            ['nome'=>'Vigilância em Saúde','tipo'=>'tecnico'],
            ['nome'=>'Alimentação Escolar','tipo'=>'tecnico'],
            ['nome'=>'Biblioteconomia','tipo'=>'tecnico'],
            ['nome'=>'Infraestrutura Escolar','tipo'=>'tecnico'],
            ['nome'=>'Multimeios Didáticos','tipo'=>'tecnico'],
            ['nome'=>'Orientação Comunitária','tipo'=>'tecnico'],
            ['nome'=>'Secretaria Escolar','tipo'=>'tecnico'],
            ['nome'=>'Análises Químicas','tipo'=>'tecnico'],
            ['nome'=>'Automação Industrial','tipo'=>'tecnico'],
            ['nome'=>'Eletroeletrônica','tipo'=>'tecnico'],
            ['nome'=>'Eletromecânica','tipo'=>'tecnico'],
            ['nome'=>'Eletrônica','tipo'=>'tecnico'],
            ['nome'=>'Eletrotécnica','tipo'=>'tecnico'],
            ['nome'=>'Manutenção Automotiva','tipo'=>'tecnico'],
            ['nome'=>'Máquinas Navais','tipo'=>'tecnico'],
            ['nome'=>'Mecânica','tipo'=>'tecnico'],
            ['nome'=>'Mecatrônica','tipo'=>'tecnico'],
            ['nome'=>'Metalurgia','tipo'=>'tecnico'],
            ['nome'=>'Petroquímica','tipo'=>'tecnico'],
            ['nome'=>'Química','tipo'=>'tecnico'],
            ['nome'=>'Refrigeração e Climatização','tipo'=>'tecnico'],
            ['nome'=>'SistemasaGás','tipo'=>'tecnico'],
            ['nome'=>'Administração','tipo'=>'tecnico'],
            ['nome'=>'Comércio','tipo'=>'tecnico'],
            ['nome'=>'Comércio Exterior','tipo'=>'tecnico'],
            ['nome'=>'Contabilidade','tipo'=>'tecnico'],
            ['nome'=>'Cooperativismo','tipo'=>'tecnico'],
            ['nome'=>'Finanças','tipo'=>'tecnico'],
            ['nome'=>'Logística','tipo'=>'tecnico'],
            ['nome'=>'Marketing','tipo'=>'tecnico'],
            ['nome'=>'Qualidade','tipo'=>'tecnico'],
            ['nome'=>'Recursos Humanos','tipo'=>'tecnico'],
            ['nome'=>'Secretariado','tipo'=>'tecnico'],
            ['nome'=>'Seguros','tipo'=>'tecnico'],
            ['nome'=>'Serviçosde Condomínio','tipo'=>'tecnico'],
            ['nome'=>'Serviços Públicos','tipo'=>'tecnico'],
            ['nome'=>'Transações Imobiliárias','tipo'=>'tecnico'],
            ['nome'=>'Vendas','tipo'=>'tecnico'],
            ['nome'=>'Agenciamento de Viagem','tipo'=>'tecnico'],
            ['nome'=>'Cozinha','tipo'=>'tecnico'],
            ['nome'=>'Eventos','tipo'=>'tecnico'],
            ['nome'=>'Guiade Turismo','tipo'=>'tecnico'],
            ['nome'=>'Hospedagem','tipo'=>'tecnico'],
            ['nome'=>'Lazer','tipo'=>'tecnico'],
            ['nome'=>'Serviços de RestauranteeBar','tipo'=>'tecnico'],
            ['nome'=>'Informática','tipo'=>'tecnico'],
            ['nome'=>'Informática para Internet','tipo'=>'tecnico'],
            ['nome'=>'Manutenção e Suporte em Informática','tipo'=>'tecnico'],
            ['nome'=>'Programação de JogosDigitais','tipo'=>'tecnico'],
            ['nome'=>'Redesde Computadores','tipo'=>'tecnico'],
            ['nome'=>'Sistemas de Comutação','tipo'=>'tecnico'],
            ['nome'=>'Sistemas de Transmissão','tipo'=>'tecnico'],
            ['nome'=>'Telecomunicações','tipo'=>'tecnico'],
            ['nome'=>'Técnico Aeroportuário','tipo'=>'tecnico'],
            ['nome'=>'Agrimensura','tipo'=>'tecnico'],
            ['nome'=>'Carpintaria','tipo'=>'tecnico'],
            ['nome'=>'Desenho de Construção Civil','tipo'=>'tecnico'],
            ['nome'=>'Edificações','tipo'=>'tecnico'],
            ['nome'=>'Estradas','tipo'=>'tecnico'],
            ['nome'=>'Geodésia e Cartografia','tipo'=>'tecnico'],
            ['nome'=>'Geoprocessamento','tipo'=>'tecnico'],
            ['nome'=>'Hidrologia','tipo'=>'tecnico'],
            ['nome'=>'Manutenção de Aeronaves','tipo'=>'tecnico'],
            ['nome'=>'Portos','tipo'=>'tecnico'],
            ['nome'=>'Saneamento','tipo'=>'tecnico'],
            ['nome'=>'Trânsito','tipo'=>'tecnico'],
            ['nome'=>'Transporte Aquaviário','tipo'=>'tecnico'],
            ['nome'=>'Transporte de Cargas','tipo'=>'tecnico'],
            ['nome'=>'Transporte Dutoviário','tipo'=>'tecnico'],
            ['nome'=>'Transporte Ferroviário','tipo'=>'tecnico'],
            ['nome'=>'Transporte Rodoviário','tipo'=>'tecnico'],
            ['nome'=>'Comunicações Aeronáuticas','tipo'=>'tecnico'],
            ['nome'=>'Controle de TráfegoAéreo','tipo'=>'tecnico'],
            ['nome'=>'DesenhoMilitar','tipo'=>'tecnico'],
            ['nome'=>'Eletricidade e Instrumentos Aeronáuticos','tipo'=>'tecnico'],
            ['nome'=>'Equipamentos de Voo','tipo'=>'tecnico'],
            ['nome'=>'Estrutura e Pintura de Aeronaves','tipo'=>'tecnico'],
            ['nome'=>'Foto inteligência','tipo'=>'tecnico'],
            ['nome'=>'Guarda e Segurança','tipo'=>'tecnico'],
            ['nome'=>'Hidrografia','tipo'=>'tecnico'],
            ['nome'=>'Informações Aeronáuticas','tipo'=>'tecnico'],
            ['nome'=>'Manobras e Equipamentos de Convés','tipo'=>'tecnico'],
            ['nome'=>'Material Bélico','tipo'=>'tecnico'],
            ['nome'=>'Mergulho','tipo'=>'tecnico'],
            ['nome'=>'Operação de Radar','tipo'=>'tecnico'],
            ['nome'=>'Operação de Sonar','tipo'=>'tecnico'],
            ['nome'=>'Operações de Engenharia Militar','tipo'=>'tecnico'],
            ['nome'=>'Preparação Física e Desportiva Militar','tipo'=>'tecnico'],
            ['nome'=>'Sensores de Aviação','tipo'=>'tecnico'],
            ['nome'=>'Sinais Navais','tipo'=>'tecnico'],
            ['nome'=>'Sinalização Náutica','tipo'=>'tecnico'],
            ['nome'=>'Suprimento','tipo'=>'tecnico'],
            ['nome'=>'Alimentos','tipo'=>'tecnico'],
            ['nome'=>'Agroindústria','tipo'=>'tecnico'],
            ['nome'=>'Apicultura','tipo'=>'tecnico'],
            ['nome'=>'Cervejaria','tipo'=>'tecnico'],
            ['nome'=>'Confeitaria','tipo'=>'tecnico'],
            ['nome'=>'Panificação','tipo'=>'tecnico'],
            ['nome'=>'Processamento de Pescado','tipo'=>'tecnico'],
            ['nome'=>'Viticultura e Enologia','tipo'=>'tecnico'],
            ['nome'=>'Arte Circense','tipo'=>'tecnico'],
            ['nome'=>'Arte Dramática','tipo'=>'tecnico'],
            ['nome'=>'Artes Visuais','tipo'=>'tecnico'],
            ['nome'=>'Artesanato','tipo'=>'tecnico'],
            ['nome'=>'Canto','tipo'=>'tecnico'],
            ['nome'=>'Composição e Arranjo','tipo'=>'tecnico'],
            ['nome'=>'Comunicação Visual','tipo'=>'tecnico'],
            ['nome'=>'Conservação e Restauro','tipo'=>'tecnico'],
            ['nome'=>'Dança','tipo'=>'tecnico'],
            ['nome'=>'Designde Calçados','tipo'=>'tecnico'],
            ['nome'=>'Designde Embalagens','tipo'=>'tecnico'],
            ['nome'=>'Designde Interiores','tipo'=>'tecnico'],
            ['nome'=>'Design de Joias','tipo'=>'tecnico'],
            ['nome'=>'Design de Móveis','tipo'=>'tecnico'],
            ['nome'=>'Documentação Musical','tipo'=>'tecnico'],
            ['nome'=>'Fabricaçãode Instrumentos Musicais','tipo'=>'tecnico'],
            ['nome'=>'Instrumento Musical','tipo'=>'tecnico'],
            ['nome'=>'Modelagem do Vestuário','tipo'=>'tecnico'],
            ['nome'=>'Multimídia','tipo'=>'tecnico'],
            ['nome'=>'Paisagismo','tipo'=>'tecnico'],
            ['nome'=>'Processos Fotográficos','tipo'=>'tecnico'],
            ['nome'=>'Produção de Áudioe Vídeo','tipo'=>'tecnico'],
            ['nome'=>'Produção de Moda','tipo'=>'tecnico'],
            ['nome'=>'Publicidade','tipo'=>'tecnico'],
            ['nome'=>'Rádio e Televisão','tipo'=>'tecnico'],
            ['nome'=>'Regência','tipo'=>'tecnico'],
            ['nome'=>'Açúcar e Álcool','tipo'=>'tecnico'],
            ['nome'=>'Biocombustíveis','tipo'=>'tecnico'],
            ['nome'=>'Calçados','tipo'=>'tecnico'],
            ['nome'=>'Celulosee Papel','tipo'=>'tecnico'],
            ['nome'=>'Cerâmica','tipo'=>'tecnico'],
            ['nome'=>'Construção Naval','tipo'=>'tecnico'],
            ['nome'=>'Curtimento','tipo'=>'tecnico'],
            ['nome'=>'Fabricação Mecânica','tipo'=>'tecnico'],
            ['nome'=>'Impressão Gráfica','tipo'=>'tecnico'],
            ['nome'=>'Impressão Offset','tipo'=>'tecnico'],
            ['nome'=>'Joalheria','tipo'=>'tecnico'],
            ['nome'=>'Móveis','tipo'=>'tecnico'],
            ['nome'=>'Petróleo e Gás','tipo'=>'tecnico'],
            ['nome'=>'Plásticos','tipo'=>'tecnico'],
            ['nome'=>'Pré-Impressão Gráfica','tipo'=>'tecnico'],
            ['nome'=>'Tecelagem','tipo'=>'tecnico'],
            ['nome'=>'Vestuário','tipo'=>'tecnico'],
            ['nome'=>'Agricultura','tipo'=>'tecnico'],
            ['nome'=>'Agroecologia','tipo'=>'tecnico'],
            ['nome'=>'Agronegócio','tipo'=>'tecnico'],
            ['nome'=>'Agropecuária','tipo'=>'tecnico'],
            ['nome'=>'Aquicultura','tipo'=>'tecnico'],
            ['nome'=>'Cafeicultura','tipo'=>'tecnico'],
            ['nome'=>'Equipamentos Pesqueiros','tipo'=>'tecnico'],
            ['nome'=>'Florestas','tipo'=>'tecnico'],
            ['nome'=>'Fruticultura','tipo'=>'tecnico'],
            ['nome'=>'Geologia','tipo'=>'tecnico'],
            ['nome'=>'Mineração','tipo'=>'tecnico'],
            ['nome'=>'Pesca','tipo'=>'tecnico'],
            ['nome'=>'Recursos Minerais','tipo'=>'tecnico'],
            ['nome'=>'Recursos Pesqueiros','tipo'=>'tecnico'],
            ['nome'=>'Zootecnia','tipo'=>'tecnico'],
            ['nome'=>'Agronegócio','tipo'=>'tecnologo'],
            ['nome'=>'Automação Industrial','tipo'=>'tecnologo'],
            ['nome'=>'Comércio Exterior','tipo'=>'tecnologo'],
            ['nome'=>'Comunicação Institucional','tipo'=>'tecnologo'],
            ['nome'=>'Designde Produto','tipo'=>'tecnologo'],
            ['nome'=>'Eletrônica Industrial','tipo'=>'tecnologo'],
            ['nome'=>'Eletrotécnica Industrial','tipo'=>'tecnologo'],
            ['nome'=>'Fabricação Mecânica','tipo'=>'tecnologo'],
            ['nome'=>'Fotografia','tipo'=>'tecnologo'],
            ['nome'=>'Gestão Ambiental','tipo'=>'tecnologo'],
            ['nome'=>'Gestão Comercial','tipo'=>'tecnologo'],
            ['nome'=>'Gestão da Produção Industrial','tipo'=>'tecnologo'],
            ['nome'=>'Gestão da Qualidade','tipo'=>'tecnologo'],
            ['nome'=>'Gestão de Cooperativas','tipo'=>'tecnologo'],
            ['nome'=>'Gestão de Recursos Humanos','tipo'=>'tecnologo'],
            ['nome'=>'Gestão Financeira','tipo'=>'tecnologo'],
            ['nome'=>'Gestão Hospitalar','tipo'=>'tecnologo'],
            ['nome'=>'Gestão Pública','tipo'=>'tecnologo'],
            ['nome'=>'Logística','tipo'=>'tecnologo'],
            ['nome'=>'Manutenção de Aeronaves','tipo'=>'tecnologo'],
            ['nome'=>'Manutenção Industrial','tipo'=>'tecnologo'],
            ['nome'=>'Marketing','tipo'=>'tecnologo'],
            ['nome'=>'Mecânicade Precisão','tipo'=>'tecnologo'],
            ['nome'=>'Mecatrônica Industrial','tipo'=>'tecnologo'],
            ['nome'=>'Processos Ambientais','tipo'=>'tecnologo'],
            ['nome'=>'Processos Metalúrgicos','tipo'=>'tecnologo'],
            ['nome'=>'Processos Escolares','tipo'=>'tecnologo'],
            ['nome'=>'Processos Químicos','tipo'=>'tecnologo'],
            ['nome'=>'Produção de Grãos','tipo'=>'tecnologo'],
            ['nome'=>'Produção Têxtil','tipo'=>'tecnologo'],
            ['nome'=>'Radiologia','tipo'=>'tecnologo'],
            ['nome'=>'Saneamento Ambiental','tipo'=>'tecnologo'],
            ['nome'=>'Sistemas Biomédicos','tipo'=>'tecnologo'],
            ['nome'=>'Sistemas Elétricos','tipo'=>'tecnologo'],
            ['nome'=>'Segurança no Trabalho','tipo'=>'tecnologo'],
            ['nome'=>'Agronegócio','tipo'=>'graduacao'],
            ['nome'=>'Automação Industrial','tipo'=>'graduacao'],
            ['nome'=>'Comércio Exterior','tipo'=>'graduacao'],
            ['nome'=>'Comunicação Institucional','tipo'=>'graduacao'],
            ['nome'=>'Designde Produto','tipo'=>'graduacao'],
            ['nome'=>'Eletrônica Industrial','tipo'=>'graduacao'],
            ['nome'=>'Eletrotécnica Industrial','tipo'=>'graduacao'],
            ['nome'=>'Fabricação Mecânica','tipo'=>'graduacao'],
            ['nome'=>'Fotografia','tipo'=>'graduacao'],
            ['nome'=>'Gestão Ambiental','tipo'=>'graduacao'],
            ['nome'=>'Gestão Comercial','tipo'=>'graduacao'],
            ['nome'=>'Gestão da ProduçãoIndustrial','tipo'=>'graduacao'],
            ['nome'=>'Gestão da Qualidade','tipo'=>'graduacao'],
            ['nome'=>'Gestão de Cooperativas','tipo'=>'graduacao'],
            ['nome'=>'Gestão de Recursos Humanos','tipo'=>'graduacao'],
            ['nome'=>'Gestão Financeira','tipo'=>'graduacao'],
            ['nome'=>'Gestão Hospitalar','tipo'=>'graduacao'],
            ['nome'=>'GestãoPública','tipo'=>'graduacao'],
            ['nome'=>'Logística','tipo'=>'graduacao'],
            ['nome'=>'Manutenção de Aeronaves','tipo'=>'graduacao'],
            ['nome'=>'Manutenção Industrial','tipo'=>'graduacao'],
            ['nome'=>'Marketing','tipo'=>'graduacao'],
            ['nome'=>'Mecânicade Precisão','tipo'=>'graduacao'],
            ['nome'=>'Mecatrônica Industrial','tipo'=>'graduacao'],
            ['nome'=>'Processos Ambientais','tipo'=>'graduacao'],
            ['nome'=>'Processos Metalúrgicos','tipo'=>'graduacao'],
            ['nome'=>'Processos Escolares','tipo'=>'graduacao'],
            ['nome'=>'Processos Químicos','tipo'=>'graduacao'],
            ['nome'=>'Produção de Grãos','tipo'=>'graduacao'],
            ['nome'=>'Produção Têxtil','tipo'=>'graduacao'],
            ['nome'=>'Radiologia','tipo'=>'graduacao'],
            ['nome'=>'Saneamento Ambiental','tipo'=>'graduacao'],
            ['nome'=>'Sistemas Biomédicos','tipo'=>'graduacao'],
            ['nome'=>'Sistemas Elétricos','tipo'=>'graduacao'],
            ['nome'=>'Segurança no Trabalho','tipo'=>'graduacao'],
            ['nome'=>'Biomedicina','tipo'=>'graduacao'],
            ['nome'=>'Ciências biológicas','tipo'=>'graduacao'],
            ['nome'=>'Ciências biológicas(licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'Educação física(bacharelado)','tipo'=>'graduacao'],
            ['nome'=>'Educação física(licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'Enfermagem','tipo'=>'graduacao'],
            ['nome'=>'Estética e cosmética(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Farmácia','tipo'=>'graduacao'],
            ['nome'=>'Fisioterapia','tipo'=>'graduacao'],
            ['nome'=>'Gestão ambiental(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Gestão hospitalar','tipo'=>'graduacao'],
            ['nome'=>'Medicina veterinária','tipo'=>'graduacao'],
            ['nome'=>'Nutrição','tipo'=>'graduacao'],
            ['nome'=>'Odontologia','tipo'=>'graduacao'],
            ['nome'=>'Psicologia','tipo'=>'graduacao'],
            ['nome'=>'Radiologia','tipo'=>'graduacao'],
            ['nome'=>'Análise e desenvolvimento de sistemas(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Arquitetura e urbanismo','tipo'=>'graduacao'],
            ['nome'=>'Ciência da computação','tipo'=>'graduacao'],
            ['nome'=>'Design de interiores(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Design de produto(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Design gráfico(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Engenharia ambiental(bacharelado)','tipo'=>'graduacao'],
            ['nome'=>'Engenharia civil','tipo'=>'graduacao'],
            ['nome'=>'Engenharia deprodução','tipo'=>'graduacao'],
            ['nome'=>'Engenharia elétrica','tipo'=>'graduacao'],
            ['nome'=>'Engenharia mecânica','tipo'=>'graduacao'],
            ['nome'=>'Engenharia mecatrônica(bacharelado)','tipo'=>'graduacao'],
            ['nome'=>'Jogos digitais(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Matemática(licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'Química(bacharelado)','tipo'=>'graduacao'],
            ['nome'=>'Química(licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'Redes de computadores(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Sistemas de informação(bacharelado)','tipo'=>'graduacao'],
            ['nome'=>'Tecnologia da informação(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Artes visuais (licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'Direito','tipo'=>'graduacao'],
            ['nome'=>'Fotografia(tecnológico)','tipo'=>'graduacao'],
            ['nome'=>'Geografia','tipo'=>'graduacao'],
            ['nome'=>'Geografia(licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'História(licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'Letras–português e inglês(licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'Pedagogia(licenciatura)','tipo'=>'graduacao'],
            ['nome'=>'Serviço social','tipo'=>'graduacao'],
        ];

        DB::table('cursos')->insert($register);
    }
}
